spring:
  application:
    name: trading

  datasource:
    url: jdbc:postgresql://localhost:5432/trading
    username: postgres
    password: Whatwhat45678

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: DEBUG



stripe:
  api:
    key: sk_test_51PKgYvIBgeEIZAi80XZOWAAo4rm7WTrxZsDqkTJ1SexOlwZrWc13njmTbmm7vBGdYf8k4RTroM6qEg1uAtd1vMfb0059jiBsRC


razorpay:
  api:
    key: razorpay api key
    secret: razorpay api secret